### PR TITLE
Hotfix for parsing Z3. Not a good fix

### PR DESCRIPTION
**Pull request by Jaxan**
I noticed that the parser for the `Z3` output doesn't work well in the total order symmetry. The reason is that we use the `read` function for a rational, which only works if the string is of the form `n % m`. However, `Z3` may occasionally output a floating point value, so `read` will break. (Note that, we do parse it correctly, we simply don't cast it correctly.)

The hotfix I used to workaround this is not elegant, but works. So we probably want a more robust solution.

PS: I realised that floating point numbers are actually a pretty good model for the dense linear order. They are truncations of the dyadic rational numbers (which is a dense linear order).

### CODE REVIEW

**Comment by szynwelski** [comment]
Could you send me the exact output of the solver for which `read` does not work?

**Comment by Jaxan** [comment]
I didn't dig that deep. I assumed this part of the code was to blame (it crashed with `Prelude.read: no match` or something along those lines), so I fixed it right away.

I can try to reproduce it after the weekend. Is there a way to see the queries to z3? Might be nice to know as well.

**Comment by szynwelski** [comment]
I've attached [hslogger](https://hackage.haskell.org/package/hslogger-1.2.10) library to `NLambda` to log SMT queries. We have now new commands available `showSmtInfo` and `hideSmtInfo` to show/hide SMT messages. We can also add [LogHandler](https://hackage.haskell.org/package/hslogger-1.2.10/docs/System-Log-Handler.html#t:LogHandler) to redirect these messages to the given file.

Sample code:
```
main = do
        showSmtInfo
        let [a,b,c] = fmap atom ["a","b","c"]
        let formula = (eq a b /\ eq a c) ==> eq b c
        print $ isTrue formula
        print $ simplify formula
```

**Comment by Jaxan** [comment]
Thanks a lot! This is a very useful tool.

I was able to reproduce the crash (I reformatted the output manually), see below. I realised that the problem is not with the `.0` at all. But it's simply the fact that `1` (this is the actual input for `read`) cannot be parsed as a rational number, since it does not have a denominator.

```
SMT INPUT:
(set-option :smt.auto-config false)
(set-option :smt.mbqi false)
(set-option :pp.min-alias-size 1000000)
(set-option :pp.max-depth 1000000)
(set-logic LRA)
(declare-const v0_1_98 Real)
(declare-const v0_2_98 Real)
(declare-const v1_1_ Real)
(declare-const v1_2_ Real)
(assert (and (> v0_1_98 v0_2_98)(or (and (< v0_1_98 v0_2_98)(< v1_1_ v1_2_))(and (>= v0_1_98 v0_2_98)(>= v1_1_ v1_2_)))(or (and (= v0_1_98 v0_2_98)(= v1_1_ v1_2_))(and (not (= v0_1_98 v0_2_98))(not (= v1_1_ v1_2_))))))
(check-sat)
(get-model)

SMT OUTPUT:
sat
(model 
  (define-fun v0_2_98 () Real
    (- 1.0))
  (define-fun v0_1_98 () Real
    0.0)
  (define-fun v1_1_ () Real
    1.0)
  (define-fun v1_2_ () Real
    0.0)
)

Prelude.read: no parse
```

**Comment by szynwelski** [comment]
You were right. There was a problem with parsing integers as a rational number. Fixed.

**Pull request closed without merging**
